ALTER TABLE order_lifecycle_events
    ADD COLUMN IF NOT EXISTS environment SMALLINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS exchange SMALLINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS market SMALLINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS position_side SMALLINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS side TEXT NOT NULL DEFAULT '';
