ALTER TABLE order_intents
  ADD COLUMN IF NOT EXISTS post_only BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS good_till_date TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS reduce_only BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE order_attempts
  ADD COLUMN IF NOT EXISTS post_only BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS good_till_date TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS reduce_only BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS risk_status TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS risk_reasons_json JSONB NOT NULL DEFAULT '[]'::jsonb;

ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS post_only BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS good_till_date TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS reduce_only BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS recovery_status TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS recovery_started_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS next_check_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS recovery_deadline_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_recovery_error TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS force_closed_at TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS idx_orders_recovery_due
  ON orders (next_check_at)
  WHERE recovery_status IN ('OPEN', 'PARTIALLY_FILLED', 'FILL_PENDING', 'FEE_MISSING', 'RECOVERING');
